[tool.poetry]
name = "namedatcolor"
version = "0.1.0"
description = ""
authors = ["Jérôme Deuchnord <git@deuchnord.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

